### ISSUE TITLE
Clean up now-unused packages

### ISSUE THREAD

**Issue by roobre** [txqueuelen/stateless-dns#88]
We should probably clean up the now-unused packages
![image](https://github.com/txqueuelen/stateless-dns/assets/969721/24ca5115-42be-435a-9fdd-c0cd28809527)

**Comment by kang-makes** [comment]
![screenshot of an error deleting the package. Content of the screenshot is below.](https://github.com/txqueuelen/stateless-dns/assets/53659978/d8d1a781-713d-4481-8c75-ccc67cd71cc2)

> Publicly visible packages with a version with more than 5000 downloads cannot be deleted. contact GitHub support for further assistance

I removed anything I could remove. Closing.

**Comment by kang-makes** [comment]
I was able to remove it by changing visibility to internal and then removing it.

Awesome :D

**Comment by roobre** [comment]
![image](https://github.com/txqueuelen/stateless-dns/assets/969721/f1e5db76-1058-437e-8020-324fb80d1ec6)
